// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.14.0
// source: company/nested1/nested2/contract.proto

package nested2

import (
	company "company"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type CompanyMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CompEnum company.CompanyEnum `protobuf:"varint,1,opt,name=compEnum,proto3,enum=company.CompanyEnum" json:"compEnum,omitempty"`
}

func (x *CompanyMessage) Reset() {
	*x = CompanyMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_company_nested1_nested2_contract_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CompanyMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompanyMessage) ProtoMessage() {}

func (x *CompanyMessage) ProtoReflect() protoreflect.Message {
	mi := &file_company_nested1_nested2_contract_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompanyMessage.ProtoReflect.Descriptor instead.
func (*CompanyMessage) Descriptor() ([]byte, []int) {
	return file_company_nested1_nested2_contract_proto_rawDescGZIP(), []int{0}
}

func (x *CompanyMessage) GetCompEnum() company.CompanyEnum {
	if x != nil {
		return x.CompEnum
	}
	return company.CompanyEnum_VAR1
}

var File_company_nested1_nested2_contract_proto protoreflect.FileDescriptor

var file_company_nested1_nested2_contract_proto_rawDesc = []byte{
	0x0a, 0x26, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x31, 0x2f, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61,
	0x63, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64, 0x31, 0x2e, 0x6e, 0x65, 0x73, 0x74, 0x65, 0x64,
	0x32, 0x1a, 0x14, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x42, 0x0a, 0x0e, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x30, 0x0a, 0x08, 0x63, 0x6f, 0x6d,
	0x70, 0x45, 0x6e, 0x75, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x14, 0x2e, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x45, 0x6e, 0x75,
	0x6d, 0x52, 0x08, 0x63, 0x6f, 0x6d, 0x70, 0x45, 0x6e, 0x75, 0x6d, 0x42, 0x09, 0x5a, 0x07, 0x6e,
	0x65, 0x73, 0x74, 0x65, 0x64, 0x32, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_company_nested1_nested2_contract_proto_rawDescOnce sync.Once
	file_company_nested1_nested2_contract_proto_rawDescData = file_company_nested1_nested2_contract_proto_rawDesc
)

func file_company_nested1_nested2_contract_proto_rawDescGZIP() []byte {
	file_company_nested1_nested2_contract_proto_rawDescOnce.Do(func() {
		file_company_nested1_nested2_contract_proto_rawDescData = protoimpl.X.CompressGZIP(file_company_nested1_nested2_contract_proto_rawDescData)
	})
	return file_company_nested1_nested2_contract_proto_rawDescData
}

var file_company_nested1_nested2_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_company_nested1_nested2_contract_proto_goTypes = []interface{}{
	(*CompanyMessage)(nil),   // 0: company.nested1.nested2.CompanyMessage
	(company.CompanyEnum)(0), // 1: company.CompanyEnum
}
var file_company_nested1_nested2_contract_proto_depIdxs = []int32{
	1, // 0: company.nested1.nested2.CompanyMessage.compEnum:type_name -> company.CompanyEnum
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_company_nested1_nested2_contract_proto_init() }
func file_company_nested1_nested2_contract_proto_init() {
	if File_company_nested1_nested2_contract_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_company_nested1_nested2_contract_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CompanyMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_company_nested1_nested2_contract_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_company_nested1_nested2_contract_proto_goTypes,
		DependencyIndexes: file_company_nested1_nested2_contract_proto_depIdxs,
		MessageInfos:      file_company_nested1_nested2_contract_proto_msgTypes,
	}.Build()
	File_company_nested1_nested2_contract_proto = out.File
	file_company_nested1_nested2_contract_proto_rawDesc = nil
	file_company_nested1_nested2_contract_proto_goTypes = nil
	file_company_nested1_nested2_contract_proto_depIdxs = nil
}
